// export { createSimplr } from './ngx'
export { Simplr } from './simplr'
export { Resolver } from './resolver'
export { Wrapper } from './wrapper'
export { SimplrOptions } from './common'
export { Adapter, AdapterForNgrxStore, AdapterForTesting } from './adapters'
export { SimplrModule } from './modules'
// export { provideSimplr, provideSimplrForTesting } from './ngx'
