export { Simplr } from './simplr'
export { SyncValueOrResolver as Resolver } from './resolver'
export { Wrapper } from './wrapper'
export { SimplrOptions } from './common'
export { Adapter, AdapterForNgrxStore, AdapterForTesting } from './adapters'
export { SimplrModule } from './simplr.module'
